### ISSUE TITLE
Update readme around watchtower

### ISSUE THREAD

**Issue by herkalurk** [SickGear/SickGear.Docker#36]
According to [watchtower docker page](https://hub.docker.com/r/centurylink/watchtower/), you don't need to specify which containers to watch.  See below docker-compose file that keeps my containers up to date (including sickgear) without specifying any container.

```
version: "3"
services:
  watchtower:
    container_name: watchtower
    image: centurylink/watchtower:latest
    logging:
      driver: journald
      options: {}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
```
